import { Injectable } from '@angular/core';
import { jsPDF } from 'jspdf';

export interface InvoiceData {
  invoiceNumber?: string;
  date?: string;
  customerName?: string;
  items?: Array<{ description: string; quantity: number; price: number }>;
  total?: number;
}

@Injectable({
  providedIn: 'root'
})
export class PdfService {
  constructor() {}

  /**
   * Generates an invoice PDF using jsPDF and returns a Blob.
   * This is the recommended approach for mobile compatibility.
   * 
   * @param data - Invoice data to populate the PDF
   * @returns Blob object containing the PDF
   */
  generateInvoicePdf(data: InvoiceData): Blob {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('INVOICE', 105, 20, { align: 'center' });
    
    // Invoice details
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Invoice #: ${data.invoiceNumber || 'INV-001'}`, 20, 40);
    doc.text(`Date: ${data.date || new Date().toLocaleDateString()}`, 20, 50);
    doc.text(`Customer: ${data.customerName || 'Sample Customer'}`, 20, 60);
    
    // Line separator
    doc.setLineWidth(0.5);
    doc.line(20, 70, 190, 70);
    
    // Items header
    doc.setFont('helvetica', 'bold');
    doc.text('Description', 20, 80);
    doc.text('Qty', 130, 80);
    doc.text('Price', 160, 80);
    
    // Items
    doc.setFont('helvetica', 'normal');
    let yPos = 90;
    const items = data.items || [
      { description: 'Sample Item 1', quantity: 2, price: 50.00 },
      { description: 'Sample Item 2', quantity: 1, price: 75.00 },
      { description: 'Sample Item 3', quantity: 3, price: 25.00 }
    ];
    
    items.forEach((item, index) => {
      doc.text(item.description, 20, yPos);
      doc.text(item.quantity.toString(), 135, yPos);
      doc.text(`$${item.price.toFixed(2)}`, 160, yPos);
      yPos += 10;
    });
    
    // Total
    doc.setLineWidth(0.5);
    doc.line(20, yPos + 5, 190, yPos + 5);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    const total = data.total || items.reduce((sum, item) => sum + (item.quantity * item.price), 0);
    doc.text(`Total: $${total.toFixed(2)}`, 160, yPos + 15);
    
    // Footer
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('Thank you for your business!', 105, 280, { align: 'center' });
    doc.text('Generated by Thesis Project PDF Service', 105, 287, { align: 'center' });
    
    // Return as Blob (BEST for mobile)
    return doc.output('blob');
  }

  /**
   * Alternative method: Returns ArrayBuffer
   * Good for advanced processing or custom file handling
   */
  generateInvoicePdfAsArrayBuffer(data: InvoiceData): ArrayBuffer {
    const doc = new jsPDF();
    this.buildInvoicePdf(doc, data);
    return doc.output('arraybuffer');
  }

  /**
   * Alternative method: Returns Data URI (Base64 string)
   * WARNING: Can crash on large files on mobile devices
   * Use only for small PDFs or web-only applications
   */
  generateInvoicePdfAsDataUri(data: InvoiceData): string {
    const doc = new jsPDF();
    this.buildInvoicePdf(doc, data);
    return doc.output('datauristring');
  }

  /**
   * Helper method to build PDF content (DRY principle)
   * Used by alternative generation methods
   */
  private buildInvoicePdf(doc: jsPDF, data: InvoiceData): void {
    // Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('INVOICE', 105, 20, { align: 'center' });
    
    // Invoice details
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Invoice #: ${data.invoiceNumber || 'INV-001'}`, 20, 40);
    doc.text(`Date: ${data.date || new Date().toLocaleDateString()}`, 20, 50);
    doc.text(`Customer: ${data.customerName || 'Sample Customer'}`, 20, 60);
    
    // Line separator
    doc.setLineWidth(0.5);
    doc.line(20, 70, 190, 70);
    
    // Items header
    doc.setFont('helvetica', 'bold');
    doc.text('Description', 20, 80);
    doc.text('Qty', 130, 80);
    doc.text('Price', 160, 80);
    
    // Items
    doc.setFont('helvetica', 'normal');
    let yPos = 90;
    const items = data.items || [
      { description: 'Sample Item 1', quantity: 2, price: 50.00 },
      { description: 'Sample Item 2', quantity: 1, price: 75.00 },
      { description: 'Sample Item 3', quantity: 3, price: 25.00 }
    ];
    
    items.forEach((item) => {
      doc.text(item.description, 20, yPos);
      doc.text(item.quantity.toString(), 135, yPos);
      doc.text(`$${item.price.toFixed(2)}`, 160, yPos);
      yPos += 10;
    });
    
    // Total
    doc.setLineWidth(0.5);
    doc.line(20, yPos + 5, 190, yPos + 5);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    const total = data.total || items.reduce((sum, item) => sum + (item.quantity * item.price), 0);
    doc.text(`Total: $${total.toFixed(2)}`, 160, yPos + 15);
    
    // Footer
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('Thank you for your business!', 105, 280, { align: 'center' });
    doc.text('Generated by Thesis Project PDF Service', 105, 287, { align: 'center' });
  }

  /**
   * Generates a custom inspection report PDF with images placeholder
   * Demonstrates more complex PDF generation
   */
  generateInspectionReportPdf(reportData: {
    projectName?: string;
    inspector?: string;
    date?: string;
    findings?: string[];
  }): Blob {
    const doc = new jsPDF();
    
    // Header with colored background
    doc.setFillColor(41, 128, 185);
    doc.rect(0, 0, 210, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('INSPECTION REPORT', 105, 20, { align: 'center' });
    
    // Reset text color
    doc.setTextColor(0, 0, 0);
    
    // Report metadata
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Project: ${reportData.projectName || 'Sample Building Inspection'}`, 20, 45);
    doc.text(`Inspector: ${reportData.inspector || 'John Doe, P.E.'}`, 20, 55);
    doc.text(`Date: ${reportData.date || new Date().toLocaleDateString()}`, 20, 65);
    
    // Findings section
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Findings:', 20, 80);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    let yPos = 90;
    const findings = reportData.findings || [
      'No structural cracks detected in main support beams',
      'Minor surface deterioration on south-facing wall',
      'Waterproofing membrane shows signs of wear',
      'Recommended: Schedule follow-up inspection in 6 months'
    ];
    
    findings.forEach((finding, index) => {
      const wrapped = doc.splitTextToSize(`${index + 1}. ${finding}`, 170);
      doc.text(wrapped, 20, yPos);
      yPos += wrapped.length * 7;
    });
    
    // Images placeholder
    doc.setFont('helvetica', 'bold');
    doc.text('Attached Images:', 20, yPos + 10);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    doc.text('[Image placeholders - In production, use doc.addImage() to embed actual photos]', 20, yPos + 20);
    
    // Footer
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('This report is generated electronically and is valid without a signature.', 105, 280, { align: 'center' });
    
    return doc.output('blob');
  }
}
